FROM golang:1.24.0-alpine

WORKDIR /go/src/app

RUN apk add --no-cache gcc musl-dev && \
    go install github.com/air-verse/air@latest

ENV GO111MODULE=on
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
