// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"gosample/internal/delivery/http/handlers"
	auth3 "gosample/internal/domain/auth"
	"gosample/internal/infrastructure/auth"
	"gosample/internal/infrastructure/config"
	"gosample/internal/infrastructure/db"
	auth2 "gosample/internal/usecase/auth"
	"gosample/internal/usecase/class"
	"gosample/internal/usecase/user"
)

// Injectors from wire.go:

// InitializeApp resolves all dependencies via Wire.
// config.Load → *config.Config → db.NewDatabase → *gorm.DB → repositories → usecases → handlers.
func InitializeApp() (*Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	gormDB, err := db.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	iUserRepository := db.NewGormUserRepository(gormDB)
	iUserUseCase := user.NewUserUseCase(iUserRepository)
	userHandler := handlers.NewUserHandler(iUserUseCase)
	iGoogleVerifier := auth.NewGoogleVerifier()
	iRoleRepository := db.NewGormCasbinRepository(gormDB)
	iPermissionService := auth.NewPermissionService()
	ijwtService := auth.NewJWTService(configConfig)
	iGoogleAuthUseCase := auth2.NewGoogleAuthUseCase(iGoogleVerifier, iUserRepository, iRoleRepository, iPermissionService, ijwtService)
	authHandler := handlers.NewAuthHandler(iGoogleAuthUseCase)
	iClassRepository := db.NewGormClassRepository(gormDB)
	iClassUseCase := class.NewClassUseCase(iClassRepository)
	classHandler := handlers.NewClassHandler(iClassUseCase)
	combinedHandler := handlers.NewCombinedHandler(userHandler, authHandler, classHandler)
	application := NewApplication(gormDB, combinedHandler, ijwtService)
	return application, nil
}

// wire.go:

type Application struct {
	DB         *gorm.DB
	Handler    *handlers.CombinedHandler
	JWTService auth3.IJWTService
}

func NewApplication(db2 *gorm.DB, handler *handlers.CombinedHandler, jwtService auth3.IJWTService) *Application {
	return &Application{
		DB:         db2,
		Handler:    handler,
		JWTService: jwtService,
	}
}

// UserSet bundles all providers for the User component.
var UserSet = wire.NewSet(db.NewGormUserRepository, user.NewUserUseCase, handlers.NewUserHandler)

// AuthSet bundles all providers for the Google Auth component.
var AuthSet = wire.NewSet(auth.NewGoogleVerifier, auth.NewPermissionService, db.NewGormCasbinRepository, auth2.NewGoogleAuthUseCase, handlers.NewAuthHandler)

// JWTSet bundles the JWT service provider.
var JWTSet = wire.NewSet(auth.NewJWTService)

// ClassSet bundles all providers for the Class component.
var ClassSet = wire.NewSet(db.NewGormClassRepository, class.NewClassUseCase, handlers.NewClassHandler)
