// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"gosample/internal/delivery/http/handlers"
	"gosample/internal/infrastructure/db"
	"gosample/internal/usecase/user"
)

// Injectors from wire.go:

// InitializeApp resolves database connection, repository, usecase, and handler.
func InitializeApp() (*Application, error) {
	gormDB, err := db.NewDatabase()
	if err != nil {
		return nil, err
	}
	iUserRepository := db.NewGormUserRepository(gormDB)
	iUserUseCase := user.NewUserUseCase(iUserRepository)
	userHandler := handlers.NewUserHandler(iUserUseCase)
	application := NewApplication(gormDB, userHandler)
	return application, nil
}

// wire.go:

type Application struct {
	DB          *gorm.DB
	UserHandler *handlers.UserHandler
}

func NewApplication(db2 *gorm.DB, handler *handlers.UserHandler) *Application {
	return &Application{
		DB:          db2,
		UserHandler: handler,
	}
}

// UserSet bundles all providers for the User component.
var UserSet = wire.NewSet(db.NewGormUserRepository, user.NewUserUseCase, handlers.NewUserHandler)
